version: "3.4"

networks:
  Avantys:
    external: false

services:
  zookeeper:
    container_name: zookeeper-container-avantys
    networks:
      - Avantys
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka-container-avantys
    networks:
      - Avantys
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  db:
    networks:
      - Avantys
    ports:
      - 3306:3306
    container_name: mysql-container-avantys
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    networks:
      - Avantys
    container_name: adminer-container-avantys
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql-container-avantys

  mongo:
    container_name: mongo-container-avantys
    ports:
      - 27017:27017
    networks:
      - Avantys
    image: mongo
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-container-avantys
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - Avantys

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local